# Generated by Django 4.1.5 on 2023-01-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='set_id',
            field=models.IntegerField(default=0),
        ),
    ]
