# Generated by Django 4.1.5 on 2023-01-09 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaires', '0002_response_set_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='set_id',
            new_name='set',
        ),
    ]
