# Generated by Django 4.1.5 on 2023-01-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaires', '0003_rename_set_id_response_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='set',
        ),
        migrations.AddField(
            model_name='examination',
            name='comment_after',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='examination',
            name='comment_before',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
