# Generated by Django 4.1.5 on 2023-01-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaires', '0004_remove_response_set_examination_comment_after_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('question', 'id')},
        ),
        migrations.AddField(
            model_name='choice',
            name='section_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
