# Generated by Django 4.1.5 on 2023-01-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaires', '0005_alter_choice_options_choice_section_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='section_text',
        ),
        migrations.AddField(
            model_name='question',
            name='section_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
